default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dev_ops
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: discord_recruitment_bot_development

production:
  <<: *default
  database: discord_recruitment_bot_production
  username: ops
  password: <%= ENV['DATABASE_PASSWORD'] %>
