food_porn:
  rare_word:
    - 白いお皿
  base_word: 飯テロ
  words:
    - 焼き鳥
    - ラーメン
    - パスタ
    - うどん
    - ステーキ
    - ハンバーガー
    - ケーキ
    - パンケーキ
    - パフェ
    - 寿司
    - ピザ
    - 焼き飯
    - チャーハン
    - おにぎり
    - てんぷら
    - ドーナッツ
    - 牛丼
    - ハンバーグ
    - オムライス
    - 中華料理
    - カレーライス
    - 焼肉
