name: build

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: utyosu/build-rails:latest

    steps:
    - uses: actions/checkout@v1

    - name: set coverall repo token
      run: 'echo "repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}" > .coveralls.yml'

    - name: run test
      run: . tools/ci/test.sh
      env:
        CI: true
